//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooks.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Books_Users_Rating = new HashSet<Books_Users_Rating>();
            this.Comments = new HashSet<Comment>();
            this.Authors = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public int PublisherId { get; set; }
        public string ImageURL { get; set; }
        public string DownloadURL { get; set; }
        public Nullable<System.Guid> UploaderUserId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<Books_Users_Rating> Books_Users_Rating { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
