//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooks.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_Users_Rating
    {
        public int BookId { get; set; }
        public System.Guid UserId { get; set; }
        public int Rating { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Book Book { get; set; }
    }
}
